-- MySQL Script generated by MySQL Workbench
-- Sat Sep 21 17:09:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Adress1` VARCHAR(45) NOT NULL,
  `Adress2` VARCHAR(45) NULL,
  `Tel1` VARCHAR(45) NOT NULL,
  `Tel2` VARCHAR(45) NULL,
  `CreatedAt` DATE NULL,
  `UpdatetAt` VARCHAR(45) NULL,
  `DeletedAt` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `email_UNIQUE` (`Email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agency` (
  `idAgency` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Adress` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Tel` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NULL,
  `CreatedAt` DATE NULL,
  `UpdatedAt` DATE NULL,
  `DeletedAt` DATE NULL,
  PRIMARY KEY (`idAgency`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TypeTransport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TypeTransport` (
  `idTypeTransport` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NULL,
  `CreatedAt` DATE NULL,
  `UpdatedAt` DATE NULL,
  `DeletedAt` DATE NULL,
  PRIMARY KEY (`idTypeTransport`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Country` (
  `idCountry` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `createdAt` DATE NULL,
  `updatedAt` DATE NULL,
  PRIMARY KEY (`idCountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `idDepartment` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `createdAt` DATE NULL,
  `updatedAt` DATE NULL,
  `country` INT NOT NULL,
  PRIMARY KEY (`idDepartment`, `country`),
  INDEX `fk_department_Country1_idx` (`country` ASC) ,
  CONSTRAINT `fk_department_country`
    FOREIGN KEY (`country`)
    REFERENCES `mydb`.`Country` (`idCountry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`City` (
  `idCity` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `CreatedAt` VARCHAR(45) NULL,
  `updatedAt` VARCHAR(45) NULL,
  `department` INT NOT NULL,
  PRIMARY KEY (`idCity`, `department`),
  INDEX `fk_City_department1_idx` (`department` ASC) ,
  CONSTRAINT `fk_City_department1`
    FOREIGN KEY (`department`)
    REFERENCES `mydb`.`Department` (`idDepartment`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Arrondissement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Arrondissement` (
  `idArrondissement` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `createdAt` DATE NULL,
  `updatedAt` DATE NULL,
  `City` INT NOT NULL,
  PRIMARY KEY (`idArrondissement`, `City`),
  INDEX `fk_arrondissement_City1_idx` (`City` ASC) ,
  CONSTRAINT `fk_arrondissement_city`
    FOREIGN KEY (`City`)
    REFERENCES `mydb`.`City` (`idCity`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`District`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`District` (
  `idDistrict` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `createdAt` DATE NULL,
  `updatedAt` DATE NULL,
  `Arrondissement` INT NOT NULL,
  PRIMARY KEY (`idDistrict`, `Arrondissement`),
  INDEX `fk_District_Arrondissement1_idx` (`Arrondissement` ASC) ,
  CONSTRAINT `fk_district_arrondissement1`
    FOREIGN KEY (`Arrondissement`)
    REFERENCES `mydb`.`Arrondissement` (`City`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Point`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Point` (
  `idPoint` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `CreatedAt` VARCHAR(45) NULL,
  `UpdatedAt` VARCHAR(45) NULL,
  `district` INT NOT NULL,
  `type` ENUM("embarquement", "debarquement") NULL,
  PRIMARY KEY (`idPoint`, `district`),
  INDEX `fk_Point_District1_idx` (`district` ASC) ,
  CONSTRAINT `fk_point_district`
    FOREIGN KEY (`district`)
    REFERENCES `mydb`.`District` (`idDistrict`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Trajet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Trajet` (
  `IdTrajet` INT NOT NULL,
  `DateDepart` DATE NOT NULL,
  `HourDepart` VARCHAR(45) NOT NULL,
  `DateArrived` DATE NOT NULL,
  `HourArrived` VARCHAR(45) NOT NULL,
  `Duration` VARCHAR(45) NOT NULL,
  `PriceAdulte` VARCHAR(45) NOT NULL,
  `PriceChild` VARCHAR(45) NOT NULL,
  `Nbr_places` INT NOT NULL,
  `embarquement` INT NOT NULL,
  `debarquement` INT NOT NULL,
  `Agency` INT NOT NULL,
  `createdAt` VARCHAR(45) NOT NULL,
  `updatedAt` VARCHAR(45) NULL,
  PRIMARY KEY (`IdTrajet`, `embarquement`, `debarquement`, `Agency`),
  INDEX `fk_Trajet_Point1_idx` (`embarquement` ASC) ,
  INDEX `fk_Trajet_PointEmbarquement_idx` (`debarquement` ASC) ,
  INDEX `fk_Trajet_Agency1_idx` (`Agency` ASC) ,
  CONSTRAINT `fk_Trajet_PointEmbarquement`
    FOREIGN KEY (`embarquement`)
    REFERENCES `mydb`.`Point` (`idPoint`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Trajet_PointDebarquement`
    FOREIGN KEY (`debarquement`)
    REFERENCES `mydb`.`Point` (`idPoint`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Trajet_Agency1`
    FOREIGN KEY (`Agency`)
    REFERENCES `mydb`.`Agency` (`idAgency`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TypeTransport_has_Trajet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TypeTransport_has_Trajet` (
  `TypeTransport` INT NOT NULL,
  `Trajet` INT NOT NULL,
  PRIMARY KEY (`TypeTransport`, `Trajet`),
  INDEX `fk_TypeTransport_has_Trajet_Trajet1_idx` (`Trajet` ASC) ,
  INDEX `fk_TypeTransport_has_Trajet_TypeTransport1_idx` (`TypeTransport` ASC) ,
  CONSTRAINT `fk_TypeTransport_has_Trajet_TypeTransport1`
    FOREIGN KEY (`TypeTransport`)
    REFERENCES `mydb`.`TypeTransport` (`idTypeTransport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TypeTransport_has_Trajet_Trajet1`
    FOREIGN KEY (`Trajet`)
    REFERENCES `mydb`.`Trajet` (`IdTrajet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stop` (
  `idStop` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `ordre` INT NOT NULL,
  `hourDepart` TIME NULL,
  `hourArrived` TIME NULL,
  `createdAt` DATE NULL,
  `updatedAt` DATE NULL,
  `Trajet` INT NOT NULL,
  PRIMARY KEY (`idStop`, `Trajet`),
  INDEX `fk_Stop_Trajet1_idx` (`Trajet` ASC) ,
  CONSTRAINT `fk_Stop_Trajet1`
    FOREIGN KEY (`Trajet`)
    REFERENCES `mydb`.`Trajet` (`IdTrajet`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Booking` (
  `idBooking` INT NOT NULL AUTO_INCREMENT,
  `nbreBilletAdult` INT NOT NULL,
  `nbreBilletChild` INT NOT NULL,
  `priceTotal` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `status` ENUM("success", "cancel") NOT NULL,
  `user` INT NOT NULL,
  `trajet` INT NOT NULL,
  PRIMARY KEY (`idBooking`, `user`, `trajet`),
  INDEX `fk_Booking_User1_idx` (`user` ASC) ,
  INDEX `fk_Booking_Trajet1_idx` (`trajet` ASC) ,
  CONSTRAINT `fk_Booking_User1`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Booking_Trajet1`
    FOREIGN KEY (`trajet`)
    REFERENCES `mydb`.`Trajet` (`IdTrajet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `idTicket` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM("adulte", "enfant") NOT NULL,
  `Statut` ENUM("success", "cancel") NOT NULL,
  `booking` INT NOT NULL,
  PRIMARY KEY (`idTicket`, `booking`),
  INDEX `fk_Ticket_Booking1_idx` (`booking` ASC) ,
  CONSTRAINT `fk_Ticket_Booking1`
    FOREIGN KEY (`booking`)
    REFERENCES `mydb`.`Booking` (`idBooking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passenger` (
  `idPassenger` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `typePassenger` ENUM("enfant", "adulte") NOT NULL,
  `date` DATE NULL,
  `ticket` INT NOT NULL,
  PRIMARY KEY (`idPassenger`, `ticket`),
  CONSTRAINT `fk_Passenger_Ticket1`
    FOREIGN KEY (`ticket`)
    REFERENCES `mydb`.`Ticket` (`idTicket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Payment` (
  `idPayment` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `modePayment` ENUM("MTN", "AIRTEL", "VISA") NOT NULL,
  `montant` INT NOT NULL,
  `booking` INT NOT NULL,
  PRIMARY KEY (`idPayment`, `booking`),
  INDEX `fk_Payment_Booking1_idx` (`booking` ASC) ,
  CONSTRAINT `fk_Payment_Booking1`
    FOREIGN KEY (`booking`)
    REFERENCES `mydb`.`Booking` (`idBooking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
